name: SonarCloud CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    name: Build & Sonar Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and run SonarCloud analysis
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=ArijitMahapatro_sonar-demo \
            -Dsonar.organization=arijitmahapatro \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
